### PR TITLE
Actual strategy popup

### PR DESCRIPTION
**Pull request by ccjoel**
PR to implement #8 
Let me know if there are any suggestions, or if the feature is definitely not desired (I might have to use a private fork if that's the case).

### CODE REVIEW

**Comment by dtinth** [comment]
Hello!

Sorry I was unaware of #8. We at Taskworld aren’t using `react-overlay-popup` anymore, and so this repo is no longer maintained. Instead, we now use [react-warp-portal](https://github.com/taskworld/react-warp-portal) along with [positioning-strategy](https://github.com/taskworld/positioning-strategy) which does things in a very different way.

Please feel free to use a fork, and please let me know if you wish to resurrect (i.e. take over) this project 😄

**Comment by ccjoel** [comment]
> so this repo is no longer maintained [...] and please let me know if you wish to resurrect

My team and I will brainstorm a bit and I'll get back to you. Thanks for reaching back and letting us know @dtinth.

**Comment by ccjoel** [comment]
As apparent as it may seem: my team decided to not resurrect the project. Hope the spinoff version goes well.

**Comment by dtinth** [comment]
Thanks for the update ;)

**Pull request closed without merging**
